apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: prod-default
spec:
  amiFamily: AL2
  instanceProfile: banking-karpenter-node-instance-profile
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: bankingapp-prod-eks
  securityGroupSelectorTerms:
    - tags:
        kubernetes.io/cluster/bankingapp-prod-eks: shared
  instanceStorePolicy: NVME
  userData: |
    #!/bin/bash
    /etc/eks/bootstrap.sh bankingapp-prod-eks
  tags:
    Environment: prod
    ManagedBy: karpenter
    karpenter.sh/discovery: bankingapp-prod-eks

