loki:
  auth_enabled: false
  
  # Use test schema for quick dev testing - bypasses schemaConfig requirement
  useTestSchema: true
  
  # Filesystem storage for dev (works with useTestSchema)
  storage:
    type: filesystem

  persistence:
    enabled: false

