loki:
  auth_enabled: false
  
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: filesystem  # Changed from s3 to filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  
  storage:
    type: filesystem  # Add this - must match object_store
  
  persistence:
    enabled: false
  
  ingester:
    chunk_encoding: snappy
  querier:
    max_concurrent: 4
  pattern_ingester:
    enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true

# For dev, use single binary mode (simpler)
deploymentMode: SingleBinary

singleBinary:
  replicas: 1

# Disable distributed components for dev
ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0

bloomPlanner:
  replicas: 0
bloomBuilder:
  replicas: 0
bloomGateway:
  replicas: 0

backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

gateway:
  service:
    type: ClusterIP  # Use ClusterIP for dev, not LoadBalancer