loki:
  auth_enabled: false
  
  storage:
    type: s3
    bucketNames:
      loki: prod-loki-storage-063630846340
    s3:
      endpoint: s3.us-east-1.amazonaws.com
      region: us-east-1
      s3ForcePathStyle: false
      secretAccessKey: ""
      accessKeyId: ""

  serviceAccount:
    create: true
    name: loki
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::063630846340:role/prod-loki-s3-access-role

  persistence:
    enabled: true
    size: 100Gi

