loki:
  auth_enabled: false
  
  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: boltdb-shipper
        object_store: s3
        schema: v11
        index:
          prefix: loki_index_
          period: 24h
  
  storage:
    type: s3
    bucketNames:
      loki: stag-loki-storage-063630846340
    s3:
      endpoint: s3.us-east-1.amazonaws.com
      region: us-east-1
      s3ForcePathStyle: false
      secretAccessKey: ""
      accessKeyId: ""

  serviceAccount:
    create: true
    name: loki
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::063630846340:role/stag-loki-s3-access-role

  persistence:
    enabled: true
    size: 50Gi  
    storageClassName: gp3

