apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rbac-prod
  namespace: argocd
spec:
  project: platform-prod-project
  source:
    repoURL: https://github.com/YonatanDas/Banking-Microservices-Platform.git
    targetRevision: main
    path: access/rbac
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system  # Cluster-scoped resources are deployed here
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - ServerSideApply=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

