apiVersion: v1
kind: LimitRange
metadata:
  name: monitoring-limit-range
  namespace: monitoring
  labels:
    app: monitoring
spec:
  limits:
    - default:
        cpu: "500m"      # Reduce from "1" to "500m"
        memory: 1Gi     # Reduce from 2Gi to 1Gi
      defaultRequest:
        cpu: "100m"      # Reduce from "200m" to "100m"
        memory: 256Mi    # Reduce from 512Mi to 256Mi
      max:
        cpu: "2"
        memory: 4Gi
      min:
        cpu: "100m"
        memory: 128Mi
      type: Container