apiVersion: v1
kind: ResourceQuota
metadata:
  name: monitoring-resource-quota
  namespace: monitoring
  labels:
    app: monitoring
spec:
  hard:
    requests.cpu: "12"
    requests.memory: 24Gi
    limits.cpu: "24"
    limits.memory: "48Gi"
    persistentvolumeclaims: "5"
    pods: "30"
    services: "25"

