opentelemetry-collector:
  mode: daemonset
  
  image:
    repository: otel/opentelemetry-collector-contrib
    tag: "0.95.0"  # or latest stable version
  
  config:
    file: |
      {{- .Files.Get "config-dev.yaml" | nindent 6 }}
  
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

