opentelemetry-collector:
  mode: daemonset
  
  config:
    file: |
      {{- .Files.Get "config-dev.yaml" | nindent 6 }}
  
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

