opentelemetry-collector:
  mode: daemonset
  
  image:
    repository: otel/opentelemetry-collector-contrib
    tag: "0.95.0"  # or latest stable version
  
  config:
    file: |
      {{- .Files.Get "config-staging.yaml" | nindent 6 }}
  
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi

