apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-prod-project  # Generic name - change "platform" to your project prefix
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
    - 'https://github.com/YonatanDas/Banking-Microservices-Platform.git'  # Update with your repository URL
  
  destinations:
    - namespace: default
      server: https://kubernetes.default.svc
    - namespace: kyverno
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
  
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: 'external-secrets.io'
      kind: ClusterSecretStore
    - group: 'kyverno.io'
      kind: ClusterPolicy
    - group: 'kyverno.io'
      kind: Policy
    - group: 'monitoring.coreos.com'
      kind: ServiceMonitor
    - group: 'monitoring.coreos.com'
      kind: PrometheusRule
  
  namespaceResourceWhitelist:
    - group: ''
      kind: '*'
    - group: 'apps'
      kind: '*'
    - group: 'autoscaling'
      kind: '*'
    - group: 'networking.k8s.io'
      kind: '*'
    - group: 'external-secrets.io'
      kind: '*'
  
  roles:
    - name: prod-admin
      description: Production environment administrator
      policies:
        - p, proj:platform-prod-project:prod-admin, applications, sync, platform-prod-project/*, allow
        - p, proj:platform-prod-project:prod-admin, applications, get, platform-prod-project/*, allow
        - p, proj:platform-prod-project:prod-admin, repositories, get, platform-prod-project/*, allow
      groups:
        - prod-team

