apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: dev-default
spec:
  template:
    metadata:
      labels:
        environment: dev
    spec:
      nodeClassRef:
        name: dev-default
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot", "on-demand"]
  limits:
    cpu: 1000
    memory: 2000Gi
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s
    expireAfter: 720h

